---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

huxtable is a package for creating HTML and LaTeX tables. It provides similar 
functionality to xtable, with a simple interface. Here's a quick example:

```{r, echo = TRUE, results = 'asis'}
library(huxtable)

ht <- huxtable(a = 1:5, b = letters[1:5])
align(ht)[,2] <- 'right'
background_color(ht) <- 'yellow'
bottom_border(ht) <- c(1, 0, 0, 0, 1)
cat(to_html(ht))
```


Or the same thing with a more dplyr-ish syntax:

```{r, echo = TRUE, results = 'asis'}
library(huxtable)
library(dplyr)

ht <- huxtable(a = 1:5, b = letters[1:5]) %>% 
      set_align(1:5, 2, 'right') %>% 
      set_background_color(1:5, 1:2, 'yellow') %>% 
      set_bottom_border(1:5, 1:2, c(1, 0, 0, 0, 1))

cat(to_html(ht))
```


To see more details, look at [testing-doc.html](http://htmlpreview.github.io/?https://github.com/hughjonesd/huxtable/blob/master/testing-doc.html) or [testing-doc.pdf](testing-doc.pdf).
