# Generated by doctest: do not edit by hand
# Please edit file in R/Workbook.R

test_that("Example: as_Workbook", {
  # Created from @doctest for `as_Workbook`
  # Source file: R/Workbook.R
  # Source line: 37
  expect_s4_class(wb <- as_Workbook(jams), "Workbook")
})

