# Generated by doctest: do not edit by hand
# Please edit file in R/subset-extract.R

test_that("Example: [.huxtable", {
  # Created from @doctest for `[.huxtable`
  # Source file: R/subset-extract.R
  # Source line: 36
  expect_equal(nrow(jams[1:3, ]), 3)
  class(jams[1:3, ])
  expect_s3_class(jams[, 1], "huxtable")
  expect_type(jams$Type, "character")
})

