# Generated by doctest: do not edit by hand
# Please edit file in R/latex-dependencies.R

test_that("Example: report_latex_dependencies", {
  # Created from @doctest for `report_latex_dependencies`
  # Source file: R/latex-dependencies.R
  # Source line: 38
  expect_snapshot(report_latex_dependencies())
})

