# Generated by doctest: do not edit by hand
# Please edit file in R/markdown.R

test_that("Example: set_markdown_contents", {
  # Created from @doctest for `set_markdown_contents`
  # Source file: R/markdown.R
  # Source line: 27
  expect_snapshot(set_markdown_contents(jams, 1, 1, "**Type** of jam"))
})

