# Generated by doctest: do not edit by hand
# Please edit file in R/flextable.R

test_that("Example: as_flextable", {
  # Created from @doctest for `as_flextable`
  # Source file: R/flextable.R
  # Source line: 32
  ht <- hux(a = 1:3, b = 1:3)
  expect_s3_class(ft <- as_flextable(ht), "flextable")
})

