# Generated by doctest: do not edit by hand
# Please edit file in R/creation.R

test_that("Example: tribble_hux", {
  # Created from @doctest for `tribble_hux`
  # Source file: R/creation.R
  # Source line: 90
  expect_s3_class(tribble_hux(~Name, ~Salary, "John Smith", 50000, "Jane Doe", 50000,
    "David Hugh-Jones", 50000, add_colnames = TRUE), "huxtable")
})

