# Generated by doctest: do not edit by hand
# Please edit file in R/brdr.R

test_that("Example: brdr", {
  # Created from @doctest for `brdr`
  # Source file: R/brdr.R
  # Source line: 16
  expect_snapshot(set_bottom_border(jams, brdr(1, "solid", "red")))
})

