# Generated by doctest: do not edit by hand
# Please edit file in R/bind-insert.R

test_that("Example: insert_column", {
  # Created from @doctest for `insert_column`
  # Source file: R/bind-insert.R
  # Source line: 80
  expect_snapshot(insert_row(jams, c("Gooseberry", 2.15), after = 1))
  expect_snapshot(insert_column(jams, c("Sugar", "50%", "60%", "40%"), after = "Price"))
  expect_snapshot(insert_column(jams, "Sugar", after = "Price", fill = "50%"))
  expect_snapshot(insert_row(jams, "Jams and prices", fill = "", colspan = 2))
})

