# Generated by doctest: do not edit by hand
# Please edit file in R/edit-defaults.R

test_that("Example: set_default_properties", {
  # Created from @doctest for `set_default_properties`
  # Source file: R/edit-defaults.R
  # Source line: 18
  old <- set_default_properties(text_color = "red", border = 0.4)
  expect_snapshot(hux(a = 1:2, b = 1:2))
  set_default_properties(old)
})

