# Generated by doctest: do not edit by hand
# Please edit file in R/column-to-header.R

test_that("Example: column_to_header", {
  # Created from @doctest for `column_to_header`
  # Source file: R/column-to-header.R
  # Source line: 14
  expect_snapshot(column_to_header(jams, "Type"))
  column_to_header(jams, "Type", text_color = "red")
  expect_snapshot(column_to_header(jams, "Price", number_format = 2, italic = TRUE,
    glue = "Price: {value}"))
})

