# Generated by doctest: do not edit by hand
# Please edit file in R/misc.R

test_that("Example: format.huxtable", {
  # Created from @doctest for `format.huxtable`
  # Source file: R/misc.R
  # Source line: 206
  expect_snapshot(cat(format(jams, output = "screen")))
  expect_snapshot(cat(format(jams, output = "md")))
})

