# Generated by doctest: do not edit by hand
# Please edit file in R/creation.R

test_that("Example: as_huxtable", {
  # Created from @doctest for `as_huxtable`
  # Source file: R/creation.R
  # Source line: 133
  dfr <- data.frame(a = 1:5, b = letters[1:5], stringsAsFactors = FALSE)
  expect_snapshot(as_huxtable(dfr))
  mx <- matrix(letters[1:12], 4, 3)
  expect_snapshot(as_huxtable(mx, add_colnames = FALSE))
  library(stats)
  tbl <- table(Wool = warpbreaks$wool, Tension = warpbreaks$tension)
  expect_snapshot(as_huxtable(tbl))
  expect_match(names(as_hux(mtcars[1:3, ], add_colnames = TRUE, add_rownames = "Car")),
  "Car", all = FALSE)
  if (requireNamespace("dplyr")) {
    iris_grp <- dplyr::group_by(iris[c(1:4, 51:54, 101:104), ], Species)
    as_hux(iris_grp, groups_to_headers = TRUE)
  }
})

