# Generated by doctest: do not edit by hand
# Please edit file in R/set-multiple.R

test_that("Example: set_all_borders", {
  # Created from @doctest for `set_all_borders`
  # Source file: R/set-multiple.R
  # Source line: 29
  ht <- as_hux(jams)
  ht <- set_all_borders(ht)
  expect_snapshot(ht)
})

