# Generated by doctest: do not edit by hand
# Please edit file in R/properties-cell.R

test_that("Example: set_contents", {
  # Created from @doctest for `set_contents`
  # Source file: R/properties-cell.R
  # Source line: 532
  expect_snapshot(set_contents(jams, 2, 1, "Blackcurrant"))
  expect_snapshot(map_contents(jams, by_regex(`.*berry` = "Snodberry")))
})

