# Generated by doctest: do not edit by hand
# Please edit file in R/bind-insert.R

test_that("Example: add_rows", {
  # Created from @doctest for `add_rows`
  # Source file: R/bind-insert.R
  # Source line: 28
  ht <- hux("Gooseberry", 2.15)
  expect_snapshot(add_rows(jams, ht))
  expect_snapshot(add_rows(jams, ht, after = 1))
  mx <- matrix(c("Sugar", "50%", "60%", "40%", "Weight (g)", 300, 250, 300), 4, 2)
  expect_snapshot(add_columns(jams, mx))
})

