# Generated by doctest: do not edit by hand
# Please edit file in R/edit-defaults.R

test_that("Example: get_default_properties", {
  # Created from @doctest for `get_default_properties`
  # Source file: R/edit-defaults.R
  # Source line: 46
  expect_false(get_default_properties("bold")$bold)
})

