# Generated by doctest: do not edit by hand
# Please edit file in R/html.R

test_that("Example: to_html", {
  # Created from @doctest for `to_html`
  # Source file: R/html.R
  # Source line: 22
  ht <- hux(a = 1:3, b = letters[1:3])
  expect_snapshot(to_html(ht))
})

