# Generated by doctest: do not edit by hand
# Please edit file in R/md.R

test_that("Example: to_md", {
  # Created from @doctest for `to_md`
  # Source file: R/md.R
  # Source line: 29
  expect_snapshot(print_md(jams))
})

