# Generated by doctest: do not edit by hand
# Please edit file in R/merge.R

test_that("Example: merge_cells", {
  # Created from @doctest for `merge_cells`
  # Source file: R/merge.R
  # Source line: 36
  ht <- hux(a = 1:3, b = 1:3)
  ht <- set_all_borders(ht, 1)
  expect_snapshot(merge_cells(ht, 2:3, 1:2))
})

