# Generated by doctest: do not edit by hand
# Please edit file in R/properties-cell.R

test_that("Example: spans", {
  # Created from @doctest for `spans`
  # Source file: R/properties-cell.R
  # Source line: 111
  letter_hux <- as_hux(matrix(LETTERS[1:9], 3, 3))
  letter_hux <- set_all_borders(letter_hux)
  letter_hux
  expect_snapshot(set_rowspan(letter_hux, 1, 1, 2))
  expect_snapshot(set_colspan(letter_hux, 1, 1, 2))
})

