# Generated by doctest: do not edit by hand
# Please edit file in R/properties-cell.R

test_that("Example: unknown", {
  # Created from @doctest for `unknown`
  # Source file: R/properties-cell.R
  # Source line: 323
  jams[3, 2] <- "~2.10~ **Sale!** 1.50"
  expect_snapshot(set_markdown(jams, 3, 2))
})

