# Generated by doctest: do not edit by hand
# Please edit file in R/merge.R

test_that("Example: merge_across", {
  # Created from @doctest for `merge_across`
  # Source file: R/merge.R
  # Source line: 75
  ht <- as_hux(matrix(1:12, 4, 3, byrow = TRUE))
  ht <- set_all_borders(ht, 1)
  expect_snapshot(merge_across(ht, 2:4, 2:3))
  expect_snapshot(merge_down(ht, 2:4, 2:3))
})

