# Generated by doctest: do not edit by hand
# Please edit file in R/creation.R

test_that("Example: huxtable", {
  # Created from @doctest for `huxtable`
  # Source file: R/creation.R
  # Source line: 47
  ht <- huxtable(column1 = 1:5, column2 = letters[1:5])
  expect_class(ht, "huxtable")
})

