# Generated by doctest: do not edit by hand
# Please edit file in R/number-format-functions.R

test_that("Example: fmt_percent", {
  # Created from @doctest for `fmt_percent`
  # Source file: R/number-format-functions.R
  # Source line: 22
  jams$Sugar <- c("Sugar content", 0.4, 0.35, 0.45)
  expect_snapshot(set_number_format(jams, -1, "Sugar", fmt_percent(1)))
})

