# Generated by doctest: do not edit by hand
# Please edit file in R/number-format-functions.R

test_that("Example: fmt_pretty", {
  # Created from @doctest for `fmt_pretty`
  # Source file: R/number-format-functions.R
  # Source line: 47
  jams$Sales <- c("Sales", 35000, 55500, 20000)
  expect_snapshot(set_number_format(jams, -1, "Sales", fmt_pretty()))
})

