# Generated by doctest: do not edit by hand
# Please edit file in R/properties-border-generics.R

test_that("Example: border-colors", {
  # Created from @doctest for `border-colors`
  # Source file: R/properties-border-generics.R
  # Source line: 168
  jams <- set_all_borders(jams)
  bottom_border_color(jams)[1, ] <- "red"
  expect_snapshot(jams)
  set_bottom_border_color(jams, "blue")
})

