# Generated by doctest: do not edit by hand
# Please edit file in R/stripes.R

test_that("Example: stripes", {
  # Created from @doctest for `stripes`
  # Source file: R/stripes.R
  # Source line: 12
  expect_snapshot(stripe_rows(jams))
  expect_snapshot(stripe_columns(jams))
  expect_snapshot(stripe_rows(jams, "red", "blue"))
})

