# Generated by doctest: do not edit by hand
# Please edit file in R/latex-dependencies.R

test_that("Example: check_latex_dependencies", {
  # Created from @doctest for `check_latex_dependencies`
  # Source file: R/latex-dependencies.R
  # Source line: 83
  expect_snapshot(check_latex_dependencies())
})

