# Generated by doctest: do not edit by hand
# Please edit file in R/set-outer.R

test_that("Example: set-outer", {
  # Created from @doctest for `set-outer`
  # Source file: R/set-outer.R
  # Source line: 17
  ht2 <- huxtable(a = 1:3, b = 1:3)
  expect_snapshot(set_outer_borders(ht2))
  expect_snapshot(set_outer_borders(ht2, 2:3, 1:2))
})

