# Generated by doctest: do not edit by hand
# Please edit file in R/screen.R

test_that("Example: to_screen", {
  # Created from @doctest for `to_screen`
  # Source file: R/screen.R
  # Source line: 38
  bottom_border(jams)[1, 1:2] <- 1
  bold(jams)[1, 1:2] <- TRUE
  jams <- map_text_color(jams, by_regex(berry = "red"))
  expect_snapshot(print_screen(jams))
})

