# Generated by doctest: do not edit by hand
# Please edit file in R/huxreg.R

test_that("Example: huxreg", {
  # Created from @doctest for `huxreg`
  # Source file: R/huxreg.R
  # Source line: 85
  if (!requireNamespace("broom")) {
    stop("Please install 'broom' to run this example.")
  }
  lm1 <- lm(mpg ~ cyl, mtcars)
  lm2 <- lm(mpg ~ cyl + hp, mtcars)
  glm1 <- glm(I(mpg > 20) ~ cyl, mtcars, family = binomial)
  expect_snapshot(huxreg(lm1, lm2, glm1))
  if (requireNamespace("sandwich") && requireNamespace("lmtest")) {
    lm_robust <- lmtest::coeftest(lm1, vcov = sandwich::vcovHC, save = TRUE)
    expect_snapshot(huxreg(lm_robust))
  }
})

