# Generated by doctest: do not edit by hand
# Please edit file in R/subset-extract.R

test_that("Example: [<-.huxtable", {
  # Created from @doctest for `[<-.huxtable`
  # Source file: R/subset-extract.R
  # Source line: 80
  prices <- huxtable(c("Price", 1.7, 2, 2.2))
  number_format(prices) <- 2
  bold(prices) <- TRUE
  jams[, 2] <- prices
  expect_snapshot(jams)
  data(jams)
  jams$Price <- c("Price", 1.7, 2, 2.2)
  expect_snapshot(jams)
})

