# Generated by doctest: do not edit by hand
# Please edit file in R/properties-border-generics.R

test_that("Example: borders", {
  # Created from @doctest for `borders`
  # Source file: R/properties-border-generics.R
  # Source line: 80
  bottom_border(jams)[1, ] <- 0.4
  expect_snapshot(jams)
  bottom_border(jams)[1, ] <- brdr(0.4, "solid", "blue")
  jams
  set_bottom_border(jams, brdr(0.4, "solid", "green"))
})

