---
title: "Quarto tester"
format: pdf
keep-md: true
---

# Kable table

Reference to @tbl-kable.

```{r}
#| tbl-cap: "Kable Cars"
#| label: tbl-kable
#| 
library(knitr)
knitr::kable(head(cars))
```

# Hux table

Reference to @tbl-hux.

```{r}
#| tbl-cap: "Huxtable Jams"
#| label: tbl-hux
library(huxtable)
jams

```

# Hux table, own label and caption

Reference to @tbl-hux-internal.

```{r}
caption(jams) <- "Caption from within R"
label(jams) <- "tbl-hux-internal"
jams

```


# Hux table, what if we did both?

R label: @tbl-hux-internal-2. Quarto label: @tbl-hux-quarto

```{r}
#| tbl-cap: "Caption from quarto"
#| label: tbl-hux-quarto
caption(jams) <- "Caption from within R"
label(jams) <- "tbl-hux-internal-2"
jams

```



# Hux table, complicated

R label: @tbl-hux-complex

```{r}
#| tbl-cap: "Caption from quarto, complex table"
#| label: tbl-hux-complex


jams |> 
  set_caption("Caption from R, complex table") |> 
  set_background_color(2, 2, "red") |> 
  set_bold(1, 2) |> 
  set_colspan(3, 1, 2) |> 
  set_bottom_border(1, everywhere) |> 
  set_width(0.9)

```
