---
title: "Quarto tester"
format: 
  pdf:
    keep-tex: true
html-table-processing: none
---

Quarto version: `r quarto::quarto_version()`.

# Builtin huxtable labels/captions

```{r}
library(huxtable)
caption(jams) <- "Table of jams"
label(jams) <- "tbl-jams"
jams

# 1.5.45
# You need to enclose caption and label in \QuartoMarkdownBase64{}.
# Then you can use any label, although Quarto processing still won't work.

# 1.4.549
# works with no label/caption at all
# works with only quarto caption, only huxtable caption, or both:
#   - quarto overrides huxtable
# works with only quarto label "jams". 
#   - But label cross-reference is not captured.
# fails with only quarto label "tbl-jams", whether or not there is a xref
# works with any huxtable label (jams/tbl-jams/tab:tbl-jams), 
#   - but xref is still not captured.
# works with quarto caption and label, so long as label is not tbl-
```

Quarto reference to @tbl-jams.
LaTeX reference to \ref{tbl-jams}.

# Quarto labels/captions

```{r}
#| label: tbljams2
#| tbl-cap: Table of Jams 2

data(jams) # clean version
jams
```

Quarto reference to @tbljams2.
LaTeX reference to \ref{tbljams2}.

