---
title: "Untitled"
author: "David Hugh-Jones"
date: "27/07/2018"
output:
  pdf_document:
    keep_tex: yes
  html_document:
    df_print: paged
keep_intermediates: yes
---

```{r setup, echo = FALSE}
# options("huxtable.knitr_output_format" = "latex")
library(huxtable)
library(dplyr)
knitr::opts_chunk$set(echo = FALSE)


```


```{r}

make <- function(nrow = 2, ncol = 2, text1 = 'Some text', text2 = 'Some more text', more_text = 'Some text') {
  ht <- hux(a = rep(text1, nrow), b = rep(text2, nrow))
  for (i in seq_len(ncol -2)) {
    ht <- cbind(ht, rep(more_text[i], nrow))
  }
  ht <- set_all_borders(ht, 1)
  ht <- set_background_color(ht, odds, everywhere, 'orange')
  ht <- set_background_color(ht, evens, everywhere, 'green')
  ht
}

long <- 'A rather long row of text which goes on...'

```

```{r}
hux("just to get our dependencies") %>% 
      set_caption("here is a longish caption... it is very long!") %>%
      set_caption_pos("topleft") %>% 
      set_position('left') %>% 
      set_caption_width(0.5)
```



```{r foo, results='asis', echo = FALSE}
ht <- hux(paste("cell", 1:3), paste("cell", 4:6)) %>% 
      set_caption("here is a long long long long caption")

poses <- c("topleft", "topright", "top", "bottomleft", "bottomright", "bottom")
cw <- c(NA, 0.5, "3in")
tposes <- c("left", "right", "centre")

# poses <- "bottomright"
# cw <- c(NA, NA)
# tposes <- "centre"

for (tpos in tposes) {
  for (pos in poses) {
    for (cap_width in cw) {
      raw <- ht %>% 
            set_caption(paste("pos", tpos, 
              "caption\\_pos", pos, "caption\\_width", cap_width)
            ) %>% 
            set_caption_pos(pos) %>% 
            set_caption_width(cap_width) %>% 
            set_position(tpos) 
      cat(knitr::knit_print(raw))
      # foo <- try(quick_pdf(raw, file = "tmp.pdf"))
      # if (inherits(foo, "try-error")) stop(foo, "tp", tpos, "cp", pos, "cw", cap_width)
    }
  }
}
```

