# Workflow for test coverage reporting
on: [push, pull_request]

name: test-coverage

jobs:
  test-coverage:
    uses: ./.github/workflows/setup-dependencies.yaml
    with:
      os: ubuntu-24.04
      r-version: 'release'
      rspm: https://packagemanager.rstudio.com/cran/__linux__/noble/latest
      extra-packages: covr
      run-command: "covr::codecov()"
    secrets: inherit
