# Workflow for test coverage reporting
on: [push, pull_request]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-24.04

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/noble/latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-r-dependencies
        with:
          r-version: 'release'
          extra-packages: covr
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: ./.github/actions/setup-latex

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
