name: 'Setup LaTeX'
description: 'Install LaTeX dependencies using tlmgr'
runs:
  using: 'composite'
  steps:
    - run: tlmgr update --self
      env:
        CTAN_REPO: https://mirror.las.iastate.edu/tex-archive/systems/texlive/tlnet/
      shell: bash
    - run: tlmgr install adjustbox ulem wrapfig threeparttable fontspec
      env:
        CTAN_REPO: https://mirror.las.iastate.edu/tex-archive/systems/texlive/tlnet/
      shell: bash
    - run: tlmgr install placeins
      env:
        CTAN_REPO: https://mirror.las.iastate.edu/tex-archive/systems/texlive/tlnet/
      shell: bash
